api/urls.py
from django.urls import path, include, re_path

from api import views
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

app_name = "api"

router = routers.DefaultRouter()

router.register(r"category", views.CategoryViewSet, basename="category")


urlpatterns = [
    # path("v1/", views.ProductListAPIView.as_view()),
    # path("v2/", views.ProductListAPIView.as_view()),
    # path("v2/<int:pk>/", views.ProductAPIUpdate.as_view()),
    path("categorylist/", views.CategoryListAPIView.as_view()),
    path("categorylist/<int:pk>/", views.CategoryAPIUpdate.as_view()),
    path("categorydelete/<int:pk>/", views.CategoryAPIDestroy.as_view()),
    # path("categorydetail/<int:pk>/", views.CategoryAPIUDetailView.as_view()),
    # path("category/", views.CategoryViewSet.as_view({"get": "list"})),
    # path("category/<int:pk>/", views.CategoryViewSet.as_view({"put": "update"})),
    path("v1/", include(router.urls)),
    path("auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path(
        "crate_payment/",
        views.CreatePaymentAPIView.as_view(),
        name="crate_payment",
    ),
    path(
        "payment_acceptance/",
        views.CreatePaymentAcceptanceView.as_view(),
    ),
]

orders/urls.py
from django.urls import include, path, reverse

from orders import views


app_name = "orders"


urlpatterns = [
    path("create_order/", views.CreateOrderView.as_view(), name="create_order"),
    # path("create-order/", views.create_order, name="create-order"),
    path("", views.OrderListView.as_view(), name="orders"),
    # path("", views.orders, name="orders"),
    path("view_order/", views.view_order, name="view_order"),
    path("order/<int:pk>/", views.OrderDetailView.as_view(), name="order"),
]

# f"{settings.DOMAIN_NAME}/{reverse('orders:create_order')}"

salemagaz/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from salemagaz import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("api/", include("api.urls", namespace="api")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("api/drf-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"


urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("registration/", views.UserRegistrationView.as_view(), name="registration"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("user-cart/", views.UserCartView.as_view(), name="user_cart"),
    path("logout/", views.logout, name="logout"),
    # path("login/", views.login, name="login"),
    # path("registration/", views.registration, name="registration"),
    # path("profile/", views.profile, name="profile"),
    # path("user-cart/", views.users_cart, name="user_cart"),
]

orders/models.py
from django.db import models
from django.urls import reverse

from carts.models import Cart
from goods.models import Products
from salemagaz import settings
from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WEY = 2
    DELIVERED = 3
    STATUS = (
        (CREATED, "Создан"),
        (PAID, "Оплачен"),
        (ON_WEY, "В пути"),
        (DELIVERED, "Доставлен"),
    )

    CARD = 0
    SBP = 1
    CASH = 2
    PAYMENT = (
        (CARD, "Картой"),
        (SBP, "СБП"),
        (CASH, "Наличными"),
    )

    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_DEFAULT,
        blank=True,
        null=True,
        verbose_name="Пользователь",
        default=None,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания заказа"
    )

    first_name = models.CharField(max_length=64, verbose_name="Имя")
    last_name = models.CharField(max_length=64)
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    address = models.CharField(max_length=256)
    note = models.TextField(verbose_name="Примечание")
    status = models.SmallIntegerField(default=CREATED, choices=STATUS)
    payment = models.SmallIntegerField(
        default=CREATED, choices=PAYMENT, verbose_name="Способ оплаты"
    )
    orders_sum = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="сумма"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["-created_timestamp"]

    def __str__(self):
        return (
            f"Заказ №{self.id}. Покупатель {self.user.first_name} {self.user.last_name}"
        )

    # def update_after_payment(self):
    #     baskets = Cart.objects.filter(user=self.user)
    #     self.status = self.PAID
    #     self.basket_history = {
    #         "purchased_item": [basket.de_json() for basket in baskets],
    #         "total_sum": float(baskets.total_sum()),
    #     }
    #     baskets.delete()
    #     self.save()

    def get_absolute_url(self):
        # f"{settings.DOMAIN_NAME}/products/category/{self.category.id}/"
        # return reverse('orders:order', kwargs={'pk': self.id}) не работает т.к. SITE_ID
        return settings.DOMAIN_NAME + reverse("orders:order", kwargs={"pk": self.id})


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(
        to=Products,
        on_delete=models.SET_DEFAULT,
        null=True,
        verbose_name="Продукт",
        default=None,
    )
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата продажи"
    )

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
from django import forms
import re


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    address = forms.CharField()
    note = forms.CharField()
    payment = forms.CharField()

    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]
        pattern = re.compile(r"^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$")
        if not pattern.match(data):
            raise forms.ValidationError("Номер телефона должен содержать только цифры")

        # pattern = re.compile(r"^\d(10)$")
        # if not pattern.match(data):
        #     raise forms.ValidationError("Неверный формат номера")

        return data

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db.models import Prefetch
from django.shortcuts import redirect, render
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, ListView

from common.mixin import CacheMixin
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem, Cart
from orders.utils import create_order
from django.http import Http404, HttpResponsePermanentRedirect, HttpResponseRedirect


def view_order(request):
    return render(request, "orders/create_order.html")


class CreateOrderView(LoginRequiredMixin, FormView):
    template_name = "orders/create_order.html"
    form_class = CreateOrderForm
    success_url = reverse_lazy("user:profile")

    def get_initial(self):
        initial = super().get_initial()

        initial["first_name"] = self.request.user.first_name
        initial["last_name"] = self.request.user.last_name
        initial["phone_number"] = self.request.user.phone_number
        return initial

    def form_valid(self, form):
        return create_order(self.request, form)

    # def form_invalid(self, form):
    #     print(form.errors)
    #     messages.error(self.request, "Заполните поля")
    #     print(messages.error(self.request, "Заполните поля"))
    #     return redirect("orders:create-order")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Salemagaz - Оформление заказа"
        return context


class OrderListView(LoginRequiredMixin, CacheMixin, ListView):
    template_name = "orders/orders.html"
    context_object_name = "orders"
    # model = Order

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     orders = cache.get(f"orders_for_user_{self.request.user.id}")
    #     if not orders:
    #         orders = Order.objects.filter(user=self.request.user).order_by("-id")
    #         cache.set(f"orders_for_user_{self.request.user.id}", orders, 60)
    #     context["orders"] = orders
    #     return context

    def get_queryset(self):
        orders = self.set_get_cache(
            Order.objects.filter(user=self.request.user).order_by("-id"),
            f"orders_for_user_{self.request.user.id}",
            10,
        )
        return orders


class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = "orders/order.html"
    context_object_name = "order"
    # model = Order

    def get_queryset(self):
        orders = (
            Order.objects.filter(pk=self.kwargs["pk"], user=self.request.user)
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            )
            .order_by("-id")
        )
        if not orders:
            orders = Order.objects.filter(user=self.request.user).order_by("-id")

            self.kwargs["pk"] = orders[0].id
            orders = (
                Order.objects.filter(pk=self.kwargs["pk"], user=self.request.user)
                .prefetch_related(
                    Prefetch(
                        "orderitem_set",
                        queryset=OrderItem.objects.select_related("product"),
                    )
                )
                .order_by("-id")
            )
        return orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"SaleMagaz - Заказ #{self.object.id}"
        return context


# @login_required()
# def orders(request):
#     orders = Order.objects.filter(user=request.user).order_by("-id")
#     context = {"orders": orders}
#     return render(request, "orders/orders.html", context=context)

# @login_required
# def create_order(request):
#     if request.method == "POST":
#         form = CreateOrderForm(data=request.POST)
#         if form.is_valid():
#             try:
#                 # пытаемся создать заказ, если хватает товара
#                 with transaction.atomic():
#                     user = request.user
#
#                     cart_items = Cart.objects.filter(user=user)
#
#                     if cart_items.exists():
#                         order = Order.objects.create(
#                             user=user,
#                             phone_number=form.cleaned_data["phone_number"],
#                             address=form.cleaned_data["address"],
#                             note=form.cleaned_data["note"],
#                             payment=form.cleaned_data["payment"],
#                             orders_sum=cart_items.total_price(),
#                         )
#
#                         for cart_item in cart_items:
#                             product = cart_item.product
#                             name = cart_item.product.name
#                             price = cart_item.product.sell_price()
#                             quantity = cart_item.quantity
#
#                             if product.quantity < quantity:
#                                 raise ValidationError(
#                                     f"Недостаточно товара {name} на складе. В наличии {product.quantity} заказали {quantity}"
#                                 )
#
#                             OrderItem.objects.create(
#                                 order=order,
#                                 product=product,
#                                 name=name,
#                                 price=price,
#                                 quantity=quantity,
#                             )
#
#                             product.quantity -= quantity
#                             product.save()
#
#                         # Очищаем корзину пользователя после создания заказа.
#                         cart_items.delete()
#
#                         messages.success(request, "Заказ оформлен!")
#                         return redirect("user:profile")
#             except ValidationError as e:
#                 messages.error(request, str(e))
#                 return redirect("cart:order")
#
#     else:
#         initial = {
#             "first_name": request.user.first_name,
#             "last_name": request.user.last_name,
#         }
#
#         form = CreateOrderForm(data=initial)
#
#     context = {
#         "title": "Home Оформление заказа",
#         "form": form,
#     }
#     return render(request, "orders/create_order.html", context=context)

orders/templates/orders/order.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}

    <main class="main__content_wrapper">

        <!-- Start breadcrumb section -->
        <section class="breadcrumb__section breadcrumb__bg">
            <div class="container">
                <div class="row row-cols-1">
                    <div class="col">
                        <div class="breadcrumb__content text-center">
                            <ul class="breadcrumb__content--menu d-flex justify-content-center">
                                <li class="breadcrumb__content--menu__items"><a href="index.html">Home</a></li>
                                <li class="breadcrumb__content--menu__items"><span>My Account</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End breadcrumb section -->
        
        <!-- my account section start -->
        <section class="my__account--section section--padding">
            <div class="container">
                 <p class="account__welcome--text">Hello, {{ user }} welcome to your dashboard!</p>
                <div class="my__account--section__inner border-radius-10 d-flex">

                    <div class="account__left--sidebar">
                        <ul class="account__menu">
                            <li class="account__menu--list active"><a href="{% url 'user:profile' %}">My Profile</a></li>
                            <li class="account__menu--list"><a href="{% url 'user:user_cart' %}">Корзина</a></li>
                            <li class="account__menu--list"><a href="{% url 'orders:orders' %}">Dashboard</a></li>
                            <li class="account__menu--list"><a href="my-account-2.html">Addresses</a></li>
                            <li class="account__menu--list"><a href="wishlist.html">Wishlist</a></li>
                            <li class="account__menu--list"><a href="{% url 'user:logout' %}">Log Out</a></li>
                        </ul>
                    </div>
                    <div class="account__wrapper">
                        <div class="account__content">
                            <h2 class="account__content--title h3 mb-20">
                                Заказ № {{ order.id }} на сумму {{ order.orders_sum }}.
                                {{ order.get_payment_display }}.
                                Статус {{ order.get_status_display }}. Дата создания {{ order.created_timestamp }}
                            </h2>
                            <div class="account__table--area">
                                <table class="account__table">
                                    <thead class="account__table--header">
                                        <tr class="account__table--header__child">
                                            <th class="account__table--header__child--items">Продукт</th>
                                            <th class="account__table--header__child--items">Цена</th>
                                            <th class="account__table--header__child--items">Количество</th>
                                            <th class="account__table--header__child--items">Сумма</th>
                                        </tr>
                                    </thead>
                                    <tbody class="account__table--body mobile__none">
                                        {% for item in order.orderitem_set.all %}

                                        <tr class="account__table--body__child">
                                            <td class="account__table--body__child--items">
                                                <a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a>
                                            </td>
                                            <td class="account__table--body__child--items">{{ item.price }}</td>
                                            <td class="account__table--body__child--items">{{ item.quantity }}</td>
                                            <td class="account__table--body__child--items">{{ item.products_price }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>

                                    <tbody class="account__table--body mobile__block">
                                        {% for item in order.orderitem_set.all %}
                                            <tr class="account__table--body__child">
                                                <td class="account__table--body__child--items">
                                                    <strong>Продукт</strong>
                                                    <span>
                                                        <a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a>
                                                    </span>
                                                </td>
                                                <td class="account__table--body__child--items">
                                                    <strong>Цена</strong>
                                                    <span>{{ item.price }}</span>
                                                </td>
                                                <td class="account__table--body__child--items">
                                                    <strong>Количество</strong>
                                                    <span>{{ item.quantity }}</span>
                                                </td>
                                                <td class="account__table--body__child--items">
                                                    <strong>Сумма</strong>
                                                    <span>{{ item.products_price }}</span>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- my account section end -->

        <!-- Start shipping section -->
        <section class="shipping__section">
            <div class="container">
                <div class="shipping__inner style2 d-flex">
                    <div class="shipping__items style2 d-flex align-items-center">
                        <div class="shipping__icon">  
                            <img src="{% static "img/other/shipping1.webp" %}" alt="icon-img">
                        </div>
                        <div class="shipping__content">
                            <h2 class="shipping__content--title h3">Free Shipping</h2>
                            <p class="shipping__content--desc">Free shipping over $100</p>
                        </div>
                    </div>
                    <div class="shipping__items style2 d-flex align-items-center">
                        <div class="shipping__icon">  
                            <img src="{% static "img/other/shipping2.webp" %}" alt="icon-img">
                        </div>
                        <div class="shipping__content">
                            <h2 class="shipping__content--title h3">Support 24/7</h2>
                            <p class="shipping__content--desc">Contact us 24 hours a day</p>
                        </div>
                    </div>
                    <div class="shipping__items style2 d-flex align-items-center">
                        <div class="shipping__icon">  
                            <img src="{% static "img/other/shipping3.webp" %}" alt="icon-img">
                        </div>
                        <div class="shipping__content">
                            <h2 class="shipping__content--title h3">100% Money Back</h2>
                            <p class="shipping__content--desc">You have 30 days to Return</p>
                        </div>
                    </div>
                    <div class="shipping__items style2 d-flex align-items-center">
                        <div class="shipping__icon">  
                            <img src="{% static "img/other/shipping4.webp" %}" alt="icon-img">
                        </div>
                        <div class="shipping__content">
                            <h2 class="shipping__content--title h3">Payment Secure</h2>
                            <p class="shipping__content--desc">We ensure secure payment</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End shipping section -->

    </main>
{% endblock %}