api/urls.py
from django.urls import path, include, re_path

from api import views
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

app_name = "api"

router = routers.DefaultRouter()

router.register(r"category", views.CategoryViewSet, basename="category")


urlpatterns = [
    # path("v1/", views.ProductListAPIView.as_view()),
    # path("v2/", views.ProductListAPIView.as_view()),
    # path("v2/<int:pk>/", views.ProductAPIUpdate.as_view()),
    path("categorylist/", views.CategoryListAPIView.as_view()),
    path("categorylist/<int:pk>/", views.CategoryAPIUpdate.as_view()),
    path("categorydelete/<int:pk>/", views.CategoryAPIDestroy.as_view()),
    # path("categorydetail/<int:pk>/", views.CategoryAPIUDetailView.as_view()),
    # path("category/", views.CategoryViewSet.as_view({"get": "list"})),
    # path("category/<int:pk>/", views.CategoryViewSet.as_view({"put": "update"})),
    path("v1/", include(router.urls)),
    path("auth/", include("djoser.urls")),
    re_path(r"^auth/", include("djoser.urls.authtoken")),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path(
        "crate_payment/",
        views.CreatePaymentAPIView.as_view(),
        name="crate_payment",
    ),
    path(
        "payment_acceptance/",
        views.CreatePaymentAcceptanceView.as_view(),
    ),
]

carts/urls.py
from django.urls import include, path

from carts import views

app_name = "carts"

urlpatterns = [
    # путь чистого джанго
    # path("cart-add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("cart-add/", views.CartAddView.as_view(), name="cart_add"),
    path("cart-change/", views.CartChangeView.as_view(), name="cart_change"),
    path("cart-remove/", views.CartRemoveView.as_view(), name="cart_remove"),
    # path("cart-add/", views.cart_add, name="cart_add"),
    # path("cart-change/", views.cart_change, name="cart_change"),
    # path("cart-remove/", views.cart_remove, name="cart_remove"),
]

main/urls.py
from django.urls import include, path
from django.views.decorators.cache import cache_page

from main import views

app_name = "main"

urlpatterns = [
    # path("", cache_page(60)(views.IndexView.as_view()), name="index"),
    path("", views.IndexView.as_view(), name="index"),
    # path('about/', views.about, name='about'),
    path("about/", cache_page(60 * 10)(views.AboutView.as_view()), name="about"),
    # path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.contact, name="contact"),
    # path('__debug__/', include('debug_toolbar.urls')),
]

payment/urls.py
from django.urls import path

from . import views


app_name = "payment"


urlpatterns = [
    path("create_payment/", views.CreatePaymentView.as_view(), name="create_payment"),
    path(
        "create_payment/<str:amount>",
        views.CreatePaymentView.as_view(),
        name="create_payment",
    ),
    # path(
    #     "payment_acceptance/",
    #     views.CreatePaymentAcceptanceView.as_view(),
    #     name="payment_acceptance",
    # ),
    path(
        "payment_acceptance/", views.crate_payment_acceptance, name="payment_acceptance"
    ),
]

salemagaz/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from salemagaz import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("api/", include("api.urls", namespace="api")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("api/drf-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = "users"


urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("registration/", views.UserRegistrationView.as_view(), name="registration"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("user-cart/", views.UserCartView.as_view(), name="user_cart"),
    path("logout/", views.logout, name="logout"),
    # path("login/", views.login, name="login"),
    # path("registration/", views.registration, name="registration"),
    # path("profile/", views.profile, name="profile"),
    # path("user-cart/", views.users_cart, name="user_cart"),
]

templates/includes/cart_button.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}
        <a class="header__account--btn minicart__open--btn" href="{% url 'user:user_cart' %}" data-offcanvas>
            <svg xmlns="http://www.w3.org/2000/svg" width="22.706" height="22.534" viewBox="0 0 14.706 13.534">
                <g  transform="translate(0 0)">
                  <g >
                    <path  data-name="Path 16787" d="M4.738,472.271h7.814a.434.434,0,0,0,.414-.328l1.723-6.316a.466.466,0,0,0-.071-.4.424.424,0,0,0-.344-.179H3.745L3.437,463.6a.435.435,0,0,0-.421-.353H.431a.451.451,0,0,0,0,.9h2.24c.054.257,1.474,6.946,1.555,7.33a1.36,1.36,0,0,0-.779,1.242,1.326,1.326,0,0,0,1.293,1.354h7.812a.452.452,0,0,0,0-.9H4.74a.451.451,0,0,1,0-.9Zm8.966-6.317-1.477,5.414H5.085l-1.149-5.414Z" transform="translate(0 -463.248)" fill="currentColor"/>
                    <path  data-name="Path 16788" d="M5.5,478.8a1.294,1.294,0,1,0,1.293-1.353A1.325,1.325,0,0,0,5.5,478.8Zm1.293-.451a.452.452,0,1,1-.431.451A.442.442,0,0,1,6.793,478.352Z" transform="translate(-1.191 -466.622)" fill="currentColor"/>
                    <path  data-name="Path 16789" d="M13.273,478.8a1.294,1.294,0,1,0,1.293-1.353A1.325,1.325,0,0,0,13.273,478.8Zm1.293-.451a.452.452,0,1,1-.431.451A.442.442,0,0,1,14.566,478.352Z" transform="translate(-2.875 -466.622)" fill="currentColor"/>
                  </g>
                </g>
            </svg>
            <span class="items__count" id="goods-in-cart-count">{{ carts.total_quantity }}</span>
            <span class="minicart__btn--text">My Cart <br> <span class="minicart__btn--text__price">{{ carts.total_price }} р</span></span>
        </a>

templates/includes/included_cart.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}
        <!-- cart section start -->
        <section class="cart__section section--padding">
            <div class="container-fluid">
                <div class="cart__section--inner" id="cart-items-container">
                    <form action="#"> 
                        <h2 class="cart__title mb-30">Shopping Cart</h2>
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="cart__table" >

                                    <table class="cart__table--inner">
                                        <thead class="cart__table--header">
                                            <tr class="cart__table--header__items">
                                                <th class="cart__table--header__list">Product</th>
                                                <th class="cart__table--header__list">Price</th>
                                                <th class="cart__table--header__list">Quantity</th>
                                                <th class="cart__table--header__list">Total</th>
                                            </tr>
                                        </thead>

                                        <tbody class="cart__table--body">
                                        {% for cart in carts %}
                                        	<tr class="cart__table--body__items">
                                            <td class="cart__table--body__list">
                                                <div class="cart__product d-flex align-items-center">
                                                    <a href="{% url 'cart:cart_remove' %}" class="remove-from-cart"
                                                       data-cart-id="{{ cart.id }}">
                                                        <button class="cart__remove--btn" aria-label="search button" type="button">
                                                            <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 24 24" width="16px" height="16px"><path d="M 4.7070312 3.2929688 L 3.2929688 4.7070312 L 10.585938 12 L 3.2929688 19.292969 L 4.7070312 20.707031 L 12 13.414062 L 19.292969 20.707031 L 20.707031 19.292969 L 13.414062 12 L 20.707031 4.7070312 L 19.292969 3.2929688 L 12 10.585938 L 4.7070312 3.2929688 z"/></svg>
                                                        </button>
                                                        {% csrf_token %}
                                                    </a>
                                                    <div class="cart__thumbnail">
                                                        <a href="{{ cart.product.get_absolute_url }}"><img class="border-radius-5" src="{{ cart.product.pics.1 }}" alt="{{ cart.product.name }}"></a>
                                                    </div>
                                                    <div class="cart__content">
                                                        <h3 class="cart__content--title h4"><a href="{{ cart.product.get_absolute_url }}">{{ cart.product.name }}</a></h3>
                                                        <span class="cart__content--variant">COLOR: Blue</span>
                                                        <span class="cart__content--variant">WEIGHT: 2 Kg</span>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="cart__table--body__list">
                                                <span class="cart__price">{{ cart.product.sell_price }} ₽</span>
                                            </td>
                                            <td class="cart__table--body__list">
                                                <div class="quantity__box">
                                                    <button type="button" class="quantity__value quickview__value--quantity decrease"
                                                            aria-label="quantity value" value="Decrease Value"
                                                            data-cart-id="{{ cart.id }}"
                                                            data-cart-change-url="{% url "cart:cart_change" %}">
                                                            {% csrf_token %}
                                                    -</button>
                                                    <label>
                                                        <input type="text" class="quantity__number quickview__value--number number" value="{{ cart.quantity }}" readonly>
                                                    </label>
                                                    <button type="button" class="quantity__value quickview__value--quantity increase"
                                                            aria-label="quantity value" value="Increase Value"
                                                            data-cart-id="{{ cart.id }}"
                                                            data-cart-change-url="{% url "cart:cart_change" %}">
                                                            {% csrf_token %}
                                                    +</button>
                                                </div>
                                            </td>
                                            <td class="cart__table--body__list">
                                                <span class="cart__price end">{{ cart.products_price }}₽</span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    <div class="continue__shopping d-flex justify-content-between">
                                        <a class="continue__shopping--link" href="{% url 'catalog:index' %}">Continue shopping</a>
                                        <button class="continue__shopping--clear" type="submit">Clear Cart</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="cart__summary border-radius-10">
                                    <div class="coupon__code mb-30">
                                        <h3 class="coupon__code--title">Coupon</h3>
                                        <p class="coupon__code--desc">Enter your coupon code if you have one.</p>
                                        <div class="coupon__code--field d-flex">
                                            <label>
                                                <input class="coupon__code--field__input border-radius-5" placeholder="Coupon code" type="text">
                                            </label>
                                            <button class="coupon__code--field__btn primary__btn" type="submit">Apply Coupon</button>
                                        </div>
                                    </div>
                                    <div class="cart__note mb-20">
                                        <h3 class="cart__note--title">Note</h3>
                                        <p class="cart__note--desc">Add special instructions for your seller...</p>
                                        <textarea class="cart__note--textarea border-radius-5"></textarea>
                                    </div>
                                    <div class="cart__summary--total mb-20">
                                        <table class="cart__summary--total__table">
                                            <tbody>
                                                <tr class="cart__summary--total__list">
                                                    <td class="cart__summary--total__title text-left">Всего товаров</td>
                                                    <td class="cart__summary--amount text-right">
                                                        <span  id="goods-in-cart-count">{{ carts.total_quantity }}</span>
                                                    </td>
                                                </tr>
                                                <tr class="cart__summary--total__list">
                                                    <td class="cart__summary--total__title text-left">Сумма без скидки</td>
                                                    <td class="cart__summary--amount text-right">{{ carts.sub_total_price }}</td>
                                                </tr>
                                                <tr class="cart__summary--total__list">
                                                    <td class="cart__summary--total__title text-left">Итого сумма</td>
                                                    <td class="cart__summary--amount text-right">{{ carts.total_price }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="cart__summary--footer">
                                        <p class="cart__summary--footer__desc">Shipping & taxes calculated at checkout</p>
                                        <ul class="d-flex justify-content-between">
{#                                            <li><button class="cart__summary--footer__btn primary__btn cart" type="submit">Update Cart</button></li>#}
                                                {% if carts %}
                                                    {% if user.balance < carts.total_price %}
                                                        {{ carts.user_balance }}
                                                        <li><a class="cart__summary--footer__btn primary__btn checkout" href="{% url 'payment:create_payment' carts.user_balance %}">
                                                            Пополнить баланс на {{ carts.user_balance }}.
                                                        </a></li>
                                                    {% else %}
                                                        <li><a class="cart__summary--footer__btn primary__btn checkout" href="{% url 'orders:create_order' %}">Перейти к оформлению.
                                                        </a></li>
                                                    {% endif %}

                                            {% endif %}
                                        </ul>
                                    </div>
                                </div> 
                            </div>
                        </div> 
                    </form> 
                </div>
            </div>     
        </section>
        <!-- cart section end -->

templates/includes/included_mini_cart.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}

<div class="offCanvas__minicart" id="exampleModal">
            <div class="minicart__header" >
                <div class="minicart__header--top d-flex jtify-content-between align-items-center">
                    <h3 class="minicart__title"> Shopping Cart</h3>
                    <button class="minicart__close--btn" aria-label="minicart close btn" data-offcanvas>
                        <svg class="minicart__close--icon" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 512 512"><path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M368 368L144 144M368 144L144 368"/></svg>
                    </button>
                </div>
                <p class="minicart__header--desc">The organic foods products are limited</p>
            </div>
    {% for cart in carts %}
            <div class="minicart__product">
                <div class="minicart__product--items d-flex">
                    <div class="minicart__thumb">
                        <a href="{{ cart.product.get_absolute_url }}"><img src="{{ cart.product.pics.1 }}" alt="{{ cart.product.name }}"></a>
                    </div>
                    <div class="minicart__text">
                        <h4 class="minicart__subtitle"><a href="{{ cart.product.get_absolute_url }}">{{ cart.product.name }}</a></h4>
                        <span class="color__variant"><b>Color:</b> Beige</span>
                        <div class="minicart__price">
                            <span class="minicart__current--price">{{ cart.product.sell_price }}</span>
                            <span class="minicart__old--price">{{ cart.product.price }}</span>
                        </div>
                        <div class="minicart__text--footer d-flex align-items-center">
                            <div class="quantity__box minicart__quantity">
                                <button type="button" class="quantity__value decrease" aria-label="quantity value" value="Decrease Value">-</button>
                                <label>
                                    <input type="number" class="quantity__number" value="{{ cart.quantity }}" data-counter />
                                </label>
                                <button type="button" class="quantity__value increase" aria-label="quantity value" value="Increase Value">+</button>
                            </div>
                            <a href="{% url 'cart:cart_remove' %}">
                                <button class="minicart__product--remove" type="button">Remove</button>
                            </a>
                        </div>
                    </div>
                </div>

            </div>

            <div class="minicart__amount">
                <div class="minicart__amount_list d-flex jtify-content-between">
                    <span>Sub Total:</span>
                    <span><b>{{ cart.sub_products_price }}</b></span>
                </div>
                <div class="minicart__amount_list d-flex jtify-content-between">
                    <span>Total:</span>
                    <span><b>{{ cart.products_price }}</b></span>
                </div>
            </div>
    {% endfor %}
    <div class="" >Итого без скидки <span><b>{{ carts.sub_total_price }}</b></span></div>
    <div class="" >Итого со скидкой <span><b>{{ carts.total_price }}</b></span></div>
    <div class="minicart__conditions text-center">
                <input class="minicart__conditions--input" id="accept" type="checkbox">
                <label class="minicart__conditions--label" for="accept">I agree with the <a class="minicart__conditions--link" href="privacy-policy.html">Privacy Policy</a></label>
            </div>
            <div class="minicart__button d-flex jtify-content-center">
                <a class="primary__btn minicart__button--link" href="{% url 'user:user_cart' %}">View cart</a>
                <a class="primary__btn minicart__button--link" href="checkout.html">Checkout</a>
            </div>
        </div>

templates/includes/notifications.html
{% load static %}
{#{% if form.non_field_errors %}#}
{#            <div class="alert alert-danger alert-dismissible fabe show custom-shadow" role="alert">#}
{#            <div class="header__bottom bg__primary" role="alert">#}
{#                {{ form.non_field_errors }}#}
{#                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>#}
{#            </div>#}
{##}
{#{% endif %}#}

{% if form.non_field_errors %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{form.non_field_errors}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
{% endif %}



{##}
{#{% if messages %} {% for message in messages %} {% if message.tags == 'success' %}#}
{#{{ message }}#}
{#{% endif %} {% if message.tags == 'warning' %}#}
{#{{ message }}#}
{#{% endif %} {% endfor %} {% else %} {% endif %}#}

<div class="container mt-4">
{#<div class="header__bottom bg__primary">#}
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}<p>sss</p>sss
                    <h>hhhh</h>
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}<p>ddd</p>dfd
                    <h>hhhh111</h>
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>